### ISSUE TITLE
Audio doesn't actually play?

### ISSUE THREAD

**Issue by jasongrishkoff** [Guichaguri/react-native-track-player#10]
I fire this:
```
load(id,song).then(function() {
  TrackPlayer.play(id)
})
```
And no music plays. The following shows up in the logs.

```
04-16 21:58:57.880  6858  8254 W MediaPlayer: Couldn't open file on client side; trying server side: java.io.FileNotFoundException: No content provider: https://api.soundcloud.com/tracks/278939950/stream?client_id=859f207b8732ba827b2bc00860808909
04-16 21:58:57.882  1620  2775 I MediaFocusControl:  AudioFocus  requestAudioFocus() from android.media.AudioManager@3e43528guichaguri.trackplayer.logic.components.FocusManager@54d0241 req=1flags=0x0
04-16 21:58:57.883  6858  6914 W MessageQueue: Handler (android.media.AudioManager$FocusEventHandlerDelegate$1) {7bff3e6} sending message to a Handler on a dead thread
04-16 21:58:57.883  6858  6914 W MessageQueue: java.lang.IllegalStateException: Handler (android.media.AudioManager$FocusEventHandlerDelegate$1) {7bff3e6} sending message to a Handler on a dead thread
04-16 21:58:57.883  6858  6914 W MessageQueue:  at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
04-16 21:58:57.883  6858  6914 W MessageQueue:  at android.os.Handler.enqueueMessage(Handler.java:631)
04-16 21:58:57.883  6858  6914 W MessageQueue:  at android.os.Handler.sendMessageAtTime(Handler.java:600)
04-16 21:58:57.883  6858  6914 W MessageQueue:  at android.os.Handler.sendMessageDelayed(Handler.java:570)
04-16 21:58:57.883  6858  6914 W MessageQueue:  at android.os.Handler.sendMessage(Handler.java:507)
04-16 21:58:57.883  6858  6914 W MessageQueue:  at android.media.AudioManager$1.dispatchAudioFocusChange(AudioManager.java:2165)
04-16 21:58:57.883  6858  6914 W MessageQueue:  at android.media.IAudioFocusDispatcher$Stub.onTransact(IAudioFocusDispatcher.java:57)
04-16 21:58:57.883  6858  6914 W MessageQueue:  at android.os.Binder.execTransact(Binder.java:453)
04-16 21:58:57.883  6858  8253 I ReactNativeJS: player-state
04-16 21:58:57.885  6858  8253 I ReactNativeJS: player-state
04-16 21:58:57.887  6858  8253 I ReactNativeJS: player-playing
04-16 21:58:58.572  1344  8264 I NuCachedSource2: new range: offset= 4476548
04-16 21:58:59.968  1344  8264 I NuCachedSource2: caching reached eos.
04-16 21:59:00.017  1344  8262 D NuPlayerDriver: notifyListener_l(0xf615af80), (3, 100, 0)
04-16 21:59:00.017  1344  8262 D NuPlayerDriver: notifyListener_l(0xf615af80), (1, 0, 0)
04-16 21:59:00.033  6858  8254 D MediaPlayer: setSubtitleAnchor in MediaPlayer
04-16 21:59:00.041  1253  1311 D hwcomposer: hw_composer sent 3491 syncs in 60s
04-16 21:59:00.076  6858  8253 I ReactNativeJS: player-state
04-16 21:59:00.079  1620  2075 I MediaFocusControl:  AudioFocus  abandonAudioFocus() from android.media.AudioManager@3e43528guichaguri.trackplayer.logic.components.FocusManager@54d0241
04-16 21:59:00.080  6858  6914 W MessageQueue: Handler (android.media.AudioManager$FocusEventHandlerDelegate$1) {7bff3e6} sending message to a Handler on a dead thread
04-16 21:59:00.080  6858  6914 W MessageQueue: java.lang.IllegalStateException: Handler (android.media.AudioManager$FocusEventHandlerDelegate$1) {7bff3e6} sending message to a Handler on a dead thread
04-16 21:59:00.080  6858  6914 W MessageQueue:  at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
04-16 21:59:00.080  6858  6914 W MessageQueue:  at android.os.Handler.enqueueMessage(Handler.java:631)
04-16 21:59:00.080  6858  6914 W MessageQueue:  at android.os.Handler.sendMessageAtTime(Handler.java:600)
04-16 21:59:00.080  6858  6914 W MessageQueue:  at android.os.Handler.sendMessageDelayed(Handler.java:570)
04-16 21:59:00.080  6858  6914 W MessageQueue:  at android.os.Handler.sendMessage(Handler.java:507)
04-16 21:59:00.080  6858  6914 W MessageQueue:  at android.media.AudioManager$1.dispatchAudioFocusChange(AudioManager.java:2165)
04-16 21:59:00.080  6858  6914 W MessageQueue:  at android.media.IAudioFocusDispatcher$Stub.onTransact(IAudioFocusDispatcher.java:57)
04-16 21:59:00.080  6858  6914 W MessageQueue:  at android.os.Binder.execTransact(Binder.java:453)
04-16 21:59:00.082  6858  8253 I ReactNativeJS: player-state
04-16 21:59:00.082  1344  1657 D NuPlayerDriver: start(0xf615af80), state is 4, eos is 0
04-16 21:59:00.082  1344  8262 I GenericSource: start
04-16 21:59:00.082  1344  8264 I NuCachedSource2: new range: offset= 0
04-16 21:59:00.084  1620  1758 I MediaFocusControl:  AudioFocus  requestAudioFocus() from android.media.AudioManager@3e43528guichaguri.trackplayer.logic.components.FocusManager@54d0241 req=1flags=0x0
04-16 21:59:00.085  6858  6869 W MessageQueue: Handler (android.media.AudioManager$FocusEventHandlerDelegate$1) {7bff3e6} sending message to a Handler on a dead thread
04-16 21:59:00.085  6858  6869 W MessageQueue: java.lang.IllegalStateException: Handler (android.media.AudioManager$FocusEventHandlerDelegate$1) {7bff3e6} sending message to a Handler on a dead thread
04-16 21:59:00.085  6858  6869 W MessageQueue:  at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
04-16 21:59:00.085  6858  6869 W MessageQueue:  at android.os.Handler.enqueueMessage(Handler.java:631)
04-16 21:59:00.085  6858  6869 W MessageQueue:  at android.os.Handler.sendMessageAtTime(Handler.java:600)
04-16 21:59:00.085  6858  6869 W MessageQueue:  at android.os.Handler.sendMessageDelayed(Handler.java:570)
04-16 21:59:00.085  6858  6869 W MessageQueue:  at android.os.Handler.sendMessage(Handler.java:507)
04-16 21:59:00.085  6858  6869 W MessageQueue:  at android.media.AudioManager$1.dispatchAudioFocusChange(AudioManager.java:2165)
04-16 21:59:00.085  6858  6869 W MessageQueue:  at android.media.IAudioFocusDispatcher$Stub.onTransact(IAudioFocusDispatcher.java:57)
04-16 21:59:00.085  6858  6869 W MessageQueue:  at android.os.Binder.execTransact(Binder.java:453)
04-16 21:59:00.093  6858  8253 I ReactNativeJS: player-pause
04-16 21:59:00.098  6858  8253 I ReactNativeJS: player-loaded
04-16 21:59:00.101  6858  8253 I ReactNativeJS: player-state
04-16 21:59:00.105  6858  8253 I ReactNativeJS: player-playing
04-16 21:59:00.680  1344  8264 I NuCachedSource2: retrying a previously failed read succeeded.
04-16 21:59:00.684  1344  8262 D NuPlayerDriver: notifyListener_l(0xf615af80), (3, 1, 0)
04-16 21:59:00.697  1344  8271 E OMXNodeInstance: setConfig(2f:google.mp3.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
04-16 21:59:00.697  1344  8271 I ACodec  : codec does not support config priority (err -2147483648)
04-16 21:59:00.698  1344  8271 I MediaCodec: MediaCodec will operate in async mode
04-16 21:59:00.722  1344  8262 D NuPlayerDriver: notifyListener_l(0xf615af80), (6, 0, 0)
04-16 21:59:00.741  6858  8253 I ReactNativeJS: player-state
04-16 21:59:00.836  1344  1655 D AudioFlinger: mixer(0xf44c0000) throttle end: throttle time(6)
04-16 21:59:01.683  1344  8262 D NuPlayerDriver: notifyListener_l(0xf615af80), (3, 31, 0)
04-16 21:59:01.699  6858  8253 I ReactNativeJS: player-state
04-16 21:59:02.683  1344  8262 D NuPlayerDriver: notifyListener_l(0xf615af80), (3, 51, 0)
04-16 21:59:02.704  6858  8253 I ReactNativeJS: player-state
04-16 21:59:03.684  1344  8262 D NuPlayerDriver: notifyListener_l(0xf615af80), (3, 73, 0)
04-16 21:59:03.689  6858  8253 I ReactNativeJS: player-state
04-16 21:59:04.276  1344  8264 I NuCachedSource2: caching reached eos.
04-16 21:59:04.685  1344  8262 D NuPlayerDriver: notifyListener_l(0xf615af80), (3, 100, 0)
04-16 21:59:04.690  6858  8253 I ReactNativeJS: player-state
```

**Comment by Guichaguri** [comment]
I though requesting focus was thread-safe. I'll look into this now

**Comment by Guichaguri** [comment]
As you can probably tell from the bugs, I haven't tested anything yet. I'll start testing every single feature, and hopefully tomorrow it will be fully working

**Comment by jasongrishkoff** [comment]
Hello, I'm back from holiday!  I just updated to the newest version and tweaked my settings according to your setup guide.  Everything's running smoothly except for the one major issue that the audio never actually starts playing?  My setup looks almost identical to the one you have in the README.

**Comment by Guichaguri** [comment]
Hey, hope you had a good time :)
Audio works fine for me, do you mind showing your code?

**Comment by jasongrishkoff** [comment]
When my app fires up, I load this (note that "store" is a mobx variable where I save all the song info).

```
TrackPlayer.onReady(async () => {
        
    // Creates a local player
    let id = await TrackPlayer.createPlayer()
        
    // Store for global mobx
    store.playerId = id

    // Sets the player as the main one
    TrackPlayer.setMain(id)

    TrackPlayer.setOptions({
        // The maximum height or width that the artwork must have. It will be resized when necessary.
        maxArtworkSize: 1000,

        // An array of media controls capabilities
        // Can contain CAPABILITY_PLAY, CAPABILITY_PAUSE, CAPABILITY_STOP, CAPABILITY_SEEK_TO,
        // CAPABILITY_SKIP_TO_NEXT, CAPABILITY_SKIP_TO_PREVIOUS, CAPABILITY_SET_RATING
        capabilities: [ 
            TrackPlayer.CAPABILITY_PLAY,
            TrackPlayer.CAPABILITY_PAUSE,
            TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
            TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS
        ],
    }) 
})
```
Then, when a user hits play on a song, I save that song info to the store, and fire the following:

```
loadSong = async() => {
    var song   = store
    var source = cleanSource(song.stream)
    store.action = 'playing'
    store.playing = true
    var id = store.playerId
    var mediaInfo = {
        id: '1234',
        url: source, // Network, usually SoundCloud API
        title: song.title,
        artist: song.artist,
        artwork: song.artwork,
        // Set cache to "null" or "undefined" to disable it
        cache: null
    }
    await TrackPlayer.load(id,mediaInfo)
    TrackPlayer.play(id)
}
```

The notification pops up with all the correct meta info, but the track never actually starts playing.

**Comment by Guichaguri** [comment]
The code still works for me. Can you check the logs for crashes or warnings?
I really need to add debug messages, that would help a lot in troubleshooting

**Comment by jasongrishkoff** [comment]
You know what, it could be emulator vs on-device. I just plugged in my Nexus 5x to test it out, and now I'm getting audio. A few other bugs to work through, but generally seems the right direction now.

Have you been testing with emulator or device?

**Comment by Guichaguri** [comment]
I've tested on both, no issues so far.

**Comment by jasongrishkoff** [comment]
Okay, I'm going to blame my computer.
