### ISSUE TITLE
setupPlayer causes crash on Android 7.0?

### ISSUE THREAD

**Issue by jasongrishkoff** [Guichaguri/react-native-track-player#39]
On Android 7.0 device (Huawei) I get the following error when I try to run `await TrackPlayer.setupPlayer({})`

```
09-09 22:44:00.556 23584 23606 I ServiceManager: Waiting for service SurfaceFlinger...
09-09 22:44:00.593   755   755 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.cast.framework.CastOptions>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/safeparcel/AbstractSafeParcelable;
09-09 22:44:00.594   755   755 I art     :   at com.google.android.gms.cast.framework.CastContext com.google.android.gms.cast.framework.CastContext.getSharedInstance(android.content.Context) ((null):-1)
09-09 22:44:00.594   755   755 I art     :   at void guichaguri.trackplayer.cast.GoogleCast.<init>(android.content.Context, guichaguri.trackplayer.logic.MediaManager) (GoogleCast.java:32)
09-09 22:44:00.594   755   755 I art     :   at void guichaguri.trackplayer.logic.MediaManager.<init>(guichaguri.trackplayer.logic.services.PlayerService) (MediaManager.java:45)
09-09 22:44:00.594   755   755 I art     :   at void guichaguri.trackplayer.logic.services.PlayerService.onCreate() (PlayerService.java:70)
09-09 22:44:00.594   755   755 I art     :   at void android.app.ActivityThread.handleCreateService(android.app.ActivityThread$CreateServiceData) (ActivityThread.java:3328)
09-09 22:44:00.594   755   755 I art     :   at void android.app.ActivityThread.-wrap5(android.app.ActivityThread, android.app.ActivityThread$CreateServiceData) (ActivityThread.java:-1)
09-09 22:44:00.594   755   755 I art     :   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1659)
09-09 22:44:00.594   755   755 I art     :   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:105)
09-09 22:44:00.594   755   755 I art     :   at void android.os.Looper.loop() (Looper.java:156)
09-09 22:44:00.594   755   755 I art     :   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6523)
09-09 22:44:00.594   755   755 I art     :   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
09-09 22:44:00.594   755   755 I art     :   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:941)
09-09 22:44:00.594   755   755 I art     :   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:831)
09-09 22:44:00.594   755   755 I art     : Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable" on path: DexPathList[[zip file "/data/app/com.decoderhq.indieshuffle-1/base.apk"],nativeLibraryDirectories=[/data/app/com.decoderhq.indieshuffle-1/lib/arm, /system/fake-libs, /data/app/com.decoderhq.indieshuffle-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/vendor/lib, /product/lib]]
09-09 22:44:00.594   755   755 I art     :   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
09-09 22:44:00.594   755   755 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
09-09 22:44:00.594   755   755 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
09-09 22:44:00.594   755   755 I art     :   at com.google.android.gms.cast.framework.CastContext com.google.android.gms.cast.framework.CastContext.getSharedInstance(android.content.Context) ((null):-1)
09-09 22:44:00.594   755   755 I art     :   at void guichaguri.trackplayer.cast.GoogleCast.<init>(android.content.Context, guichaguri.trackplayer.logic.MediaManager) (GoogleCast.java:32)
09-09 22:44:00.594   755   755 I art     :   at void guichaguri.trackplayer.logic.MediaManager.<init>(guichaguri.trackplayer.logic.services.PlayerService) (MediaManager.java:45)
09-09 22:44:00.594   755   755 I art     :   at void guichaguri.trackplayer.logic.services.PlayerService.onCreate() (PlayerService.java:70)
09-09 22:44:00.594   755   755 I art     :   at void android.app.ActivityThread.handleCreateService(android.app.ActivityThread$CreateServiceData) (ActivityThread.java:3328)
09-09 22:44:00.594   755   755 I art     :   at void android.app.ActivityThread.-wrap5(android.app.ActivityThread, android.app.ActivityThread$CreateServiceData) (ActivityThread.java:-1)
09-09 22:44:00.594   755   755 I art     :   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1659)
09-09 22:44:00.594   755   755 I art     :   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:105)
09-09 22:44:00.594   755   755 I art     :   at void android.os.Looper.loop() (Looper.java:156)
09-09 22:44:00.594   755   755 I art     :   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6523)
09-09 22:44:00.594   755   755 I art     :   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
09-09 22:44:00.594   755   755 I art     :   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:941)
09-09 22:44:00.594   755   755 I art     :   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:831)
09-09 22:44:00.594   755   755 I art     : 
09-09 22:44:00.594   755   755 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.cast.framework.CastOptions>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/safeparcel/AbstractSafeParcelable;
09-09 22:44:00.594   755   755 I art     :   at com.google.android.gms.cast.framework.CastContext com.google.android.gms.cast.framework.CastContext.getSharedInstance(android.content.Context) ((null):-1)
09-09 22:44:00.594   755   755 I art     :   at void guichaguri.trackplayer.cast.GoogleCast.<init>(android.content.Context, guichaguri.trackplayer.logic.MediaManager) (GoogleCast.java:32)
09-09 22:44:00.594   755   755 I art     :   at void guichaguri.trackplayer.logic.MediaManager.<init>(guichaguri.trackplayer.logic.services.PlayerService) (MediaManager.java:45)
09-09 22:44:00.594   755   755 I art     :   at void guichaguri.trackplayer.logic.services.PlayerService.onCreate() (PlayerService.java:70)
09-09 22:44:00.594   755   755 I art     :   at void android.app.ActivityThread.handleCreateService(android.app.ActivityThread$CreateServiceData) (ActivityThread.java:3328)
09-09 22:44:00.594   755   755 I art     :   at void android.app.ActivityThread.-wrap5(android.app.ActivityThread, android.app.ActivityThread$CreateServiceData) (ActivityThread.java:-1)
09-09 22:44:00.594   755   755 I art     :   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1659)
09-09 22:44:00.595   755   755 I art     :   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:105)
09-09 22:44:00.595   755   755 I art     :   at void android.os.Looper.loop() (Looper.java:156)
09-09 22:44:00.595   755   755 I art     :   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6523)
09-09 22:44:00.595   755   755 I art     :   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
09-09 22:44:00.595   755   755 I art     :   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:941)
09-09 22:44:00.595   755   755 I art     :   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:831)
09-09 22:44:00.595   755   755 I art     : Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable" on path: DexPathList[[zip file "/data/app/com.decoderhq.indieshuffle-1/base.apk"],nativeLibraryDirectories=[/data/app/com.decoderhq.indieshuffle-1/lib/arm, /system/fake-libs, /data/app/com.decoderhq.indieshuffle-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/vendor/lib, /product/lib]]
09-09 22:44:00.595   755   755 I art     :   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
09-09 22:44:00.595   755   755 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
09-09 22:44:00.595   755   755 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
09-09 22:44:00.595   755   755 I art     :   at com.google.android.gms.cast.framework.CastContext com.google.android.gms.cast.framework.CastContext.getSharedInstance(android.content.Context) ((null):-1)
09-09 22:44:00.595   755   755 I art     :   at void guichaguri.trackplayer.cast.GoogleCast.<init>(android.content.Context, guichaguri.trackplayer.logic.MediaManager) (GoogleCast.java:32)
09-09 22:44:00.595   755   755 I art     :   at void guichaguri.trackplayer.logic.MediaManager.<init>(guichaguri.trackplayer.logic.services.PlayerService) (MediaManager.java:45)
09-09 22:44:00.595   755   755 I art     :   at void guichaguri.trackplayer.logic.services.PlayerService.onCreate() (PlayerService.java:70)
09-09 22:44:00.595   755   755 I art     :   at void android.app.ActivityThread.handleCreateService(android.app.ActivityThread$CreateServiceData) (ActivityThread.java:3328)
09-09 22:44:00.595   755   755 I art     :   at void android.app.ActivityThread.-wrap5(android.app.ActivityThread, android.app.ActivityThread$CreateServiceData) (ActivityThread.java:-1)
09-09 22:44:00.595   755   755 I art     :   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1659)
09-09 22:44:00.595   755   755 I art     :   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:105)
09-09 22:44:00.595   755   755 I art     :   at void android.os.Looper.loop() (Looper.java:156)
09-09 22:44:00.595   755   755 I art     :   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6523)
09-09 22:44:00.595   755   755 I art     :   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
09-09 22:44:00.595   755   755 I art     :   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:941)
09-09 22:44:00.595   755   755 I art     :   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:831)
09-09 22:44:00.595   755   755 I art     : 
09-09 22:44:00.612   755   755 E CrashlyticsCore: Failed to execute task.
09-09 22:44:00.612   755   755 E CrashlyticsCore: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: No static method getBatteryLevel(Landroid/content/Context;)F in class Lio/fabric/sdk/android/services/common/CommonUtils; or its super classes (declaration of 'io.fabric.sdk.android.services.common.CommonUtils' appears in /data/app/com.decoderhq.indieshuffle-1/base.apk)
09-09 22:44:00.612   755   755 E CrashlyticsCore:       at java.util.concurrent.FutureTask.report(FutureTask.java:94)
09-09 22:44:00.612   755   755 E CrashlyticsCore:       at java.util.concurrent.FutureTask.get(FutureTask.java:178)
09-09 22:44:00.612   755   755 E CrashlyticsCore:       at com.crashlytics.android.core.CrashlyticsExecutorServiceWrapper.executeSyncLoggingException(CrashlyticsExecutorServiceWrapper.java:44)
09-09 22:44:00.612   755   755 E CrashlyticsCore:       at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:235)
09-09 22:44:00.612   755   755 E CrashlyticsCore:       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
09-09 22:44:00.612   755   755 E CrashlyticsCore:       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
09-09 22:44:00.612   755   755 E CrashlyticsCore: Caused by: java.lang.NoSuchMethodError: No static method getBatteryLevel(Landroid/content/Context;)F in class Lio/fabric/sdk/android/services/common/CommonUtils; or its super classes (declaration of 'io.fabric.sdk.android.services.common.CommonUtils' appears in /data/app/com.decoderhq.indieshuffle-1/base.apk)
09-09 22:44:00.612   755   755 E CrashlyticsCore:       at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.writeSessionEvent(CrashlyticsUncaughtExceptionHandler.java:1005)
09-09 22:44:00.612   755   755 E CrashlyticsCore:       at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.writeFatal(CrashlyticsUncaughtExceptionHandler.java:766)
09-09 22:44:00.612   755   755 E CrashlyticsCore:       at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.handleUncaughtException(CrashlyticsUncaughtExceptionHandler.java:262)
09-09 22:44:00.612   755   755 E CrashlyticsCore:       at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.access$100(CrashlyticsUncaughtExceptionHandler.java:55)
09-09 22:44:00.612   755   755 E CrashlyticsCore:       at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler$5.call(CrashlyticsUncaughtExceptionHandler.java:238)
09-09 22:44:00.612   755   755 E CrashlyticsCore:       at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler$5.call(CrashlyticsUncaughtExceptionHandler.java:235)
09-09 22:44:00.612   755   755 E CrashlyticsCore:       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-09 22:44:00.612   755   755 E CrashlyticsCore:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
09-09 22:44:00.612   755   755 E CrashlyticsCore:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
09-09 22:44:00.612   755   755 E CrashlyticsCore:       at io.fabric.sdk.android.services.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:75)
09-09 22:44:00.612   755   755 E CrashlyticsCore:       at io.fabric.sdk.android.services.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:30)
09-09 22:44:00.612   755   755 E CrashlyticsCore:       at java.lang.Thread.run(Thread.java:776)
09-09 22:44:00.613   755   755 E AndroidRuntime: FATAL EXCEPTION: main
09-09 22:44:00.613   755   755 E AndroidRuntime: Process: com.decoderhq.indieshuffle, PID: 755
09-09 22:44:00.613   755   755 E AndroidRuntime: java.lang.NoSuchMethodError: No static method zzh(Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/String; in class Lcom/google/android/gms/common/internal/zzab; or its super classes (declaration of 'com.google.android.gms.common.internal.zzab' appears in /data/app/com.decoderhq.indieshuffle-1/base.apk)
09-09 22:44:00.613   755   755 E AndroidRuntime:        at com.google.android.gms.cast.internal.zzm.<init>(Unknown Source)
09-09 22:44:00.613   755   755 E AndroidRuntime:        at com.google.android.gms.cast.internal.zzm.<init>(Unknown Source)
09-09 22:44:00.613   755   755 E AndroidRuntime:        at com.google.android.gms.cast.framework.CastContext.<clinit>(Unknown Source)
09-09 22:44:00.613   755   755 E AndroidRuntime:        at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source)
09-09 22:44:00.613   755   755 E AndroidRuntime:        at guichaguri.trackplayer.cast.GoogleCast.<init>(GoogleCast.java:32)
09-09 22:44:00.613   755   755 E AndroidRuntime:        at guichaguri.trackplayer.logic.MediaManager.<init>(MediaManager.java:45)
09-09 22:44:00.613   755   755 E AndroidRuntime:        at guichaguri.trackplayer.logic.services.PlayerService.onCreate(PlayerService.java:70)
09-09 22:44:00.613   755   755 E AndroidRuntime:        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3328)
09-09 22:44:00.613   755   755 E AndroidRuntime:        at android.app.ActivityThread.-wrap5(ActivityThread.java)
09-09 22:44:00.613   755   755 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
09-09 22:44:00.613   755   755 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:105)
09-09 22:44:00.613   755   755 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:156)
09-09 22:44:00.613   755   755 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6523)
09-09 22:44:00.613   755   755 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-09 22:44:00.613   755   755 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
09-09 22:44:00.613   755   755 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

```

**Comment by Guichaguri** [comment]
It looks like the Cast SDK was not found.
Does it work without any other native modules?

**Comment by jasongrishkoff** [comment]
The device I'm using, you mean? Not sure I understand what you mean by
other native modules.

FYI that this phone does have Google Home and I have used it for Chromecast.

I've tried a release build as well -- same crash on the device (works fine
in 8.0 emulator).

**Comment by Guichaguri** [comment]
I meant other react native modules, which can create google play service conflicts

**Comment by jasongrishkoff** [comment]
Perhaps you were right.  Doing this allowed it to boot, even though there's no "gms" if I grep anywhere in their library.

```
    compile(project(":react-native-orientation")){
        exclude group: "com.google.android.gms"
    }
```

**Comment by jasongrishkoff** [comment]
Oh no wait, I'm an idiot. The only reason it booted was because I had commented out `await TrackPlayer.setupPlayer({})`.  So, back to square one.

**Comment by jasongrishkoff** [comment]
These are my dependencies:
```
dependencies {
    compile project(':react-native-orientation')
    compile project(':react-native-fabric')
    compile(project(':react-native-fbsdk')){
      exclude(group: 'com.facebook.android', module: 'facebook-android-sdk')
    }
    compile 'com.facebook.android:facebook-android-sdk:4.22.1'
    compile project(':react-native-fabric-twitterkit')
    compile project(':react-native-vector-icons')
    compile project(':react-native-share')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile 'com.google.android.gms:play-services-cast:9.4.0'
    compile 'com.google.android.gms:play-services-auth:+' // should be at least 9.0.0
    compile(project(":react-native-google-signin")){
        exclude group: "com.google.android.gms" // very important
    }
    compile('com.crashlytics.sdk.android:crashlytics:2.5.5@aar') {
        transitive = true;
    }
    compile('com.twitter.sdk.android:twitter:2.3.1@aar') {
        transitive = true;
    }
    compile project(':react-native-track-player')
}
```
The only new one is the orientation package. Otherwise, I've been using these same dependencies for the last few months.

**Comment by Guichaguri** [comment]
Does it work with only the `react-native-track-player` module?

**Comment by jasongrishkoff** [comment]
Here's the answer: https://stackoverflow.com/questions/41408514/com-google-android-gms-common-internal-safe-parcel-safe-parcelable-not-found

As you can see above, I had:
```
    compile 'com.google.android.gms:play-services-cast:9.4.0'
    compile 'com.google.android.gms:play-services-auth:+' // should be at least 9.0.0
```
I needed to change that + to 9.4.0

**Comment by Guichaguri** [comment]
That was it? I'll make sure I add this to the troubleshooting page :)
